export const FOOD_ICONS = {
    "Fruits": ["🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐", "🍈", "🍒", "🍑", "🥭", "🍍", "🥥", "🥝", "🍅", "🥑", "🍆"],
    "Vegetables": ["🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦", "🧄", "🧅", "🍄", "🥜", "🌰"],
    "Prepared": ["🍞", "🥐", "🥖", "🫓", "🥨", "🥯", "🥞", "🧇", "🧀", "🍖", "🍗", "🥩", "🥓", "🍔", "🍟", "🍕", "🌭", "🥪", "🌮", "🌯", "🫔", "🥙", "🧆", "🥚", "🍳", "🥘", "🍲", "🫕", "🥣", "🥗", "🍿", "🧈", "🧂", "🥫"],
    "Asian": ["🍱", "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍠", "🍢", "🍣", "🍤", "🍥", "🥮", "🍡", "🥟", "🥠", "🥡"],
    "Seafood": ["🦀", "🦞", "🦐", "🦑", "🦪", "🐟"],
    "Sweets": ["🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫", "🍬", "🍭", "🍮", "🍯"],
    "Drinks": ["🍼", "🥛", "☕", "🫖", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂", "🥃", "🥤", "🧋", "🧃", "🧉", "🧊"],
    "Utensils": ["🥢", "🍽️", "🍴", "🥄", "🔪", "🏺"]
};

export const ALL_FOOD_ICONS = Object.values(FOOD_ICONS).flat();

const ICON_KEYWORDS: Record<string, string[]> = {
    "🍎": ["apple", "manzana", "red apple"],
    "🍐": ["pear", "pera"],
    "🍊": ["tangerine", "mandarin", "orange", "naranja", "mandarina"],
    "🍋": ["lemon", "limon", "limón"],
    "🍌": ["banana", "plátano", "platano"],
    "🍉": ["watermelon", "sandia", "sandía"],
    "🍇": ["grape", "uva"],
    "🍓": ["strawberry", "fresa", "frutilla"],
    "🫐": ["blueberry", "arandano", "arándano"],
    "🍈": ["melon", "melón"],
    "🍒": ["cherry", "cereza"],
    "🍑": ["peach", "durazno", "melocoton", "melocotón"],
    "🥭": ["mango"],
    "🍍": ["pineapple", "piña", "anana", "ananá"],
    "🥥": ["coconut", "coco"],
    "🥝": ["kiwi"],
    "🍅": ["tomato", "tomate"],
    "🥑": ["avocado", "palta", "aguacate"],
    "🍆": ["eggplant", "berenjena"],
    "🥔": ["potato", "papa", "patata"],
    "🥕": ["carrot", "zanahoria"],
    "🌽": ["corn", "maiz", "maíz", "choclo"],
    "🌶️": ["chili", "chile", "picante", "aji", "ají"],
    "🫑": ["bell pepper", "pimiento", "morron", "morrón"],
    "🥒": ["cucumber", "pepino"],
    "🥬": ["leafy green", "lechuga", "kale", "spinach", "espinaca", "acelga"],
    "🥦": ["broccoli", "brocoli", "brócoli"],
    "🧄": ["garlic", "ajo"],
    "🧅": ["onion", "cebolla"],
    "🍄": ["mushroom", "hongo", "champiñon", "champiñón", "seta"],
    "🥜": ["peanut", "mani", "maní", "cacahuate"],
    "🌰": ["chestnut", "castaña"],
    "🍞": ["bread", "pan", "toast", "tostada"],
    "🥐": ["croissant", "medialuna"],
    "🥖": ["baguette"],
    "🫓": ["flatbread", "arepa", "tortilla"],
    "🥨": ["pretzel"],
    "🥯": ["bagel"],
    "🥞": ["pancake", "panqueque", "hotcake"],
    "🧇": ["waffle", "gofre"],
    "🧀": ["cheese", "queso"],
    "🍖": ["meat on bone", "carne", "costilla"],
    "🍗": ["chicken leg", "pollo", "muslo"],
    "🥩": ["steak", "bife", "carne", "lomo", "solomillo", "asado"],
    "🥓": ["bacon", "panceta", "tocino"],
    "🍔": ["hamburger", "burger", "hamburguesa"],
    "🍟": ["fries", "papas fritas"],
    "🍕": ["pizza"],
    "🌭": ["hot dog", "pancho", "perrito caliente"],
    "🥪": ["sandwich", "sanguche", "sándwich"],
    "🌮": ["taco"],
    "🌯": ["burrito"],
    "🫔": ["tamale", "tamal"],
    "🥙": ["stuffed flatbread", "kebab", "shawarma"],
    "🧆": ["falafel"],
    "🥚": ["egg", "huevo"],
    "🍳": ["cooking", "fried egg", "huevo frito"],
    "🥘": ["shallow pan of food", "paella", "guiso"],
    "🍲": ["pot of food", "stew", "sopa", "caldo"],
    "🫕": ["fondue"],
    "🥣": ["bowl with spoon", "cereal", "oats", "avena", "porridge", "yogurt", "yogur"],
    "🥗": ["green salad", "salad", "ensalada"],
    "🍿": ["popcorn", "pochoclo", "palomitas"],
    "🧈": ["butter", "manteca", "mantequilla"],
    "🧂": ["salt", "sal"],
    "🥫": ["canned food", "lata", "conserva"],
    "🍱": ["bento box"],
    "🍘": ["rice cracker", "galleta de arroz"],
    "🍙": ["rice ball", "onigiri"],
    "🍚": ["rice", "arroz"],
    "🍛": ["curry rice", "curry"],
    "🍜": ["steaming bowl", "noodles", "ramen", "fideos", "pasta"],
    "🍝": ["spaghetti", "pasta", "fideos"],
    "🍠": ["roasted sweet potato", "batata", "boniato"],
    "🍢": ["oden"],
    "🍣": ["sushi"],
    "🍤": ["fried shrimp", "gamba", "langostino"],
    "🍥": ["fish cake"],
    "🥮": ["moon cake"],
    "🍡": ["dango"],
    "🥟": ["dumpling", "empanada", "gyoza"],
    "🥠": ["fortune cookie"],
    "🥡": ["takeout box"],
    "🦀": ["crab", "cangrejo"],
    "🦞": ["lobster", "langosta"],
    "🦐": ["shrimp", "camaron", "camarón"],
    "🦑": ["squid", "calamar"],
    "🦪": ["oyster", "ostra"],
    "🐟": ["fish", "pescado", "atun", "atún", "salmon", "salmón"],
    "🍦": ["soft ice cream", "helado"],
    "🍧": ["shaved ice"],
    "🍨": ["ice cream", "helado"],
    "🍩": ["doughnut", "dona", "rosquilla", "factura"],
    "🍪": ["cookie", "galleta", "galletita"],
    "🎂": ["birthday cake", "torta", "pastel"],
    "🍰": ["shortcake", "torta", "pastel"],
    "🧁": ["cupcake", "magdalena"],
    "🥧": ["pie", "tarta"],
    "🍫": ["chocolate"],
    "🍬": ["candy", "caramelo"],
    "🍭": ["lollipop", "chupetin", "chupetín"],
    "🍮": ["custard", "flan"],
    "🍯": ["honey", "miel"],
    "🍼": ["baby bottle"],
    "🥛": ["milk", "leche", "vaso de leche"],
    "☕": ["hot beverage", "coffee", "cafe", "café", "tea", "té"],
    "🫖": ["teapot", "tetera"],
    "🍵": ["teacup without handle", "matcha", "green tea", "té verde"],
    "🍶": ["sake"],
    "🍾": ["champagne"],
    "🍷": ["wine", "vino"],
    "🍸": ["cocktail", "coctel", "cóctel"],
    "🍹": ["tropical drink", "trago"],
    "🍺": ["beer", "cerveza", "birra"],
    "🍻": ["clinking beer mugs", "brindis"],
    "🥂": ["clinking glasses", "brindis"],
    "🥃": ["tumbler glass", "whisky", "whiskey"],
    "🥤": ["cup with straw", "soda", "gaseosa", "refresco", "protein", "proteina", "proteína"],
    "🧋": ["bubble tea"],
    "🧃": ["beverage box", "jugo"],
    "🧉": ["mate"],
    "🧊": ["ice", "hielo"],
    "🥢": ["chopsticks", "palillos"],
    "🍽️": ["fork and knife", "plato"],
    "🍴": ["fork and knife"],
    "🥄": ["spoon", "cuchara"],
    "🔪": ["kitchen knife", "cuchillo"],
    "🏺": ["amphora"]
};

export function getSuggestedIcon(text: string): string | null {
    const lowerText = text.toLowerCase();

    // Check for exact matches first (optional, but good for performance)

    // Iterate through keywords
    for (const [icon, keywords] of Object.entries(ICON_KEYWORDS)) {
        for (const keyword of keywords) {
            // Check if the text contains the keyword as a whole word or part of it?
            // "yogur proteico" contains "yogur".
            // Simple includes check might be enough for now.
            if (lowerText.includes(keyword)) {
                return icon;
            }
        }
    }

    return null;
}
